
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-05-21T09:10:11-1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e405e0e4e25bd7fa4b248e145b402c7ce5aa4ca4",
 "version": "v0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
