
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2019-05-16T18:09:58-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "769b62a57e5fcd0bd5af25694db20f64247bce7a",
 "version": "1.9.0b1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
