# coding: utf-8

"""
    App Center Client

    Microsoft Visual Studio App Center API  # noqa: E501

    OpenAPI spec version: preview
    Contact: benedetto.abbenanti@gmail.com
    Project Repository: https://github.com/b3nab/appcenter-sdks
"""

import pprint
import re  # noqa: F401

import six


class ItunesTeamsResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'team_id': 'string',
        'team_name': 'string'
    }

    attribute_map = {
        'team_id': 'team_id',
        'team_name': 'team_name'
    }

    def __init__(self, team_id=None, team_name=None):  # noqa: E501
        """ItunesTeamsResponse - a model defined in Swagger"""  # noqa: E501
        self._team_id = None
        self._team_name = None
        self.discriminator = None
        if team_id is not None:
            self.team_id = team_id
        if team_name is not None:
            self.team_name = team_name

    @property
    def team_id(self):
        """Gets the team_id of this ItunesTeamsResponse.  # noqa: E501

        Itunes team id.  # noqa: E501

        :return: The team_id of this ItunesTeamsResponse.  # noqa: E501
        :rtype: string
        """
        return self._team_id

    @team_id.setter
    def team_id(self, team_id):
        """Sets the team_id of this ItunesTeamsResponse.

        Itunes team id.  # noqa: E501

        :param team_id: The team_id of this ItunesTeamsResponse.  # noqa: E501
        :type: string
        """

        self._team_id = team_id

    @property
    def team_name(self):
        """Gets the team_name of this ItunesTeamsResponse.  # noqa: E501

        Itunes Team Name  # noqa: E501

        :return: The team_name of this ItunesTeamsResponse.  # noqa: E501
        :rtype: string
        """
        return self._team_name

    @team_name.setter
    def team_name(self, team_name):
        """Sets the team_name of this ItunesTeamsResponse.

        Itunes Team Name  # noqa: E501

        :param team_name: The team_name of this ItunesTeamsResponse.  # noqa: E501
        :type: string
        """

        self._team_name = team_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ItunesTeamsResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
