
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-05-13T15:30:51-0500",
 "dirty": true,
 "error": null,
 "full-revisionid": "5bd23b18ba20342f9910d8ca9312ac84b8b465ea",
 "version": "0.3.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
