
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-05-13T16:09:53+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "86fbf409219b17e054845aa875fb84816017150d",
 "version": "0.1.0-alpha.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
