# Generated by Django 2.2.1 on 2019-05-08 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0002_auto_20190508_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenRanking',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Open rankings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('rankings.ranking',),
        ),
        migrations.AlterModelOptions(
            name='adminballot',
            options={'ordering': ('poll', 'voter', 'ranking'), 'verbose_name_plural': 'Open ballots'},
        ),
        migrations.AlterUniqueTogether(
            name='ranking',
            unique_together={('poll', 'candidate')},
        ),
    ]
