# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-06-20 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_logs', '0005_auto_20171101_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='max_level',
            field=models.SmallIntegerField(choices=[(50, 'CRITICAL'), (40, 'ERROR'), (30, 'WARNING'), (20, 'INFO'), (10, 'DEBUG'), (0, 'NOTSET')], db_index=True, default=0, verbose_name='Max level'),
        ),
        migrations.AlterIndexTogether(
            name='request',
            index_together=set([('start_date', 'id')]),
        ),
    ]
