
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-05-20T10:23:50+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "a2737f619aefde30f0733fd233efa0eb5eaacdc7",
 "version": "0.0.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
