
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "2d4f8f251703392b330db7c10e4268d6fbbb6c73",
 "version": "1.6.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
