
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-05-14T13:55:16-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "d825910d21cb88c007cb1516119a41635935090f",
 "version": "1.6.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
