# coding: utf-8

"""
    App Center Client

    Microsoft Visual Studio App Center API  # noqa: E501

    OpenAPI spec version: preview
    Contact: benedetto.abbenanti@gmail.com
    Project Repository: https://github.com/b3nab/appcenter-sdks
"""

import pprint
import re  # noqa: F401

import six


class UserSettingResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'marketing_opt_in': 'string'
    }

    attribute_map = {
        'marketing_opt_in': 'marketing_opt_in'
    }

    def __init__(self, marketing_opt_in=None):  # noqa: E501
        """UserSettingResponse - a model defined in Swagger"""  # noqa: E501
        self._marketing_opt_in = None
        self.discriminator = None
        if marketing_opt_in is not None:
            self.marketing_opt_in = marketing_opt_in

    @property
    def marketing_opt_in(self):
        """Gets the marketing_opt_in of this UserSettingResponse.  # noqa: E501

        The marketing opt-in setting  # noqa: E501

        :return: The marketing_opt_in of this UserSettingResponse.  # noqa: E501
        :rtype: string
        """
        return self._marketing_opt_in

    @marketing_opt_in.setter
    def marketing_opt_in(self, marketing_opt_in):
        """Sets the marketing_opt_in of this UserSettingResponse.

        The marketing opt-in setting  # noqa: E501

        :param marketing_opt_in: The marketing_opt_in of this UserSettingResponse.  # noqa: E501
        :type: string
        """

        self._marketing_opt_in = marketing_opt_in

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserSettingResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
