# coding: utf-8

"""
    App Center Client

    Microsoft Visual Studio App Center API  # noqa: E501

    OpenAPI spec version: preview
    Contact: benedetto.abbenanti@gmail.com
    Project Repository: https://github.com/b3nab/appcenter-sdks
"""

import pprint
import re  # noqa: F401

import six


class XcodeToolset(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'xcode_scheme_containers': 'array'
    }

    attribute_map = {
        'xcode_scheme_containers': 'xcode_scheme_containers'
    }

    def __init__(self, xcode_scheme_containers=None):  # noqa: E501
        """XcodeToolset - a model defined in Swagger"""  # noqa: E501
        self._xcode_scheme_containers = None
        self.discriminator = None
        if xcode_scheme_containers is not None:
            self.xcode_scheme_containers = xcode_scheme_containers

    @property
    def xcode_scheme_containers(self):
        """Gets the xcode_scheme_containers of this XcodeToolset.  # noqa: E501

        The Xcode scheme containers  # noqa: E501

        :return: The xcode_scheme_containers of this XcodeToolset.  # noqa: E501
        :rtype: array
        """
        return self._xcode_scheme_containers

    @xcode_scheme_containers.setter
    def xcode_scheme_containers(self, xcode_scheme_containers):
        """Sets the xcode_scheme_containers of this XcodeToolset.

        The Xcode scheme containers  # noqa: E501

        :param xcode_scheme_containers: The xcode_scheme_containers of this XcodeToolset.  # noqa: E501
        :type: array
        """

        self._xcode_scheme_containers = xcode_scheme_containers

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, XcodeToolset):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
