
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-05-17T22:48:45+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "2bcf1af8a780a4d776e58a569b124bf98e4d7e6b",
 "version": "0.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
