#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup


setup(name='legacycrypt',
      version='0.3',
      description='Wrapper to the POSIX crypt library call and associated functionality.',
      author='Christian Heimes',
      author_email='christian@python.org',
      url='https://github.com/tiran/legacycrypt',
      py_modules=['legacycrypt'],
      python_requires='>=3.5',
     )
