
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-05-15T14:42:50+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "12459e147497cd3680daae19257e48b2c672ff0c",
 "version": "0.2.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
