
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "ff8762f914a10281cc8332d1d57a3b2aeb5c4a9e",
 "version": "2145"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
