
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-05-11T14:07:34-0500",
 "dirty": true,
 "error": null,
 "full-revisionid": "700134859603d1644e87bc5f18dffd1e39032ff2",
 "version": "0.3.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
