# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SubscripProtos.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SubscripProtos.proto',
  package='bean',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x14SubscripProtos.proto\x12\x04\x62\x65\x61n\"q\n\nResultBean\x12\x0f\n\x07message\x18\x01 \x01(\t\x12.\n\x0cprotocolType\x18\x02 \x01(\x0e\x32\x12.bean.ProtocolEnum:\x04\x43ONN\x12\x0c\n\x04\x62ody\x18\x03 \x01(\t\x12\x14\n\x0creplaceToken\x18\x04 \x01(\t*7\n\x0cProtocolEnum\x12\x08\n\x04\x43ONN\x10\x00\x12\x07\n\x03PUB\x10\x01\x12\x07\n\x03SUB\x10\x02\x12\x0b\n\x07\x42\x41\x43KPUB\x10\x03')
)

_PROTOCOLENUM = _descriptor.EnumDescriptor(
  name='ProtocolEnum',
  full_name='bean.ProtocolEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CONN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PUB', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUB', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BACKPUB', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=145,
  serialized_end=200,
)
_sym_db.RegisterEnumDescriptor(_PROTOCOLENUM)

ProtocolEnum = enum_type_wrapper.EnumTypeWrapper(_PROTOCOLENUM)
CONN = 0
PUB = 1
SUB = 2
BACKPUB = 3



_RESULTBEAN = _descriptor.Descriptor(
  name='ResultBean',
  full_name='bean.ResultBean',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='bean.ResultBean.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='protocolType', full_name='bean.ResultBean.protocolType', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='body', full_name='bean.ResultBean.body', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='replaceToken', full_name='bean.ResultBean.replaceToken', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=143,
)

_RESULTBEAN.fields_by_name['protocolType'].enum_type = _PROTOCOLENUM
DESCRIPTOR.message_types_by_name['ResultBean'] = _RESULTBEAN
DESCRIPTOR.enum_types_by_name['ProtocolEnum'] = _PROTOCOLENUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ResultBean = _reflection.GeneratedProtocolMessageType('ResultBean', (_message.Message,), dict(
  DESCRIPTOR = _RESULTBEAN,
  __module__ = 'SubscripProtos_pb2'
  # @@protoc_insertion_point(class_scope:bean.ResultBean)
  ))
_sym_db.RegisterMessage(ResultBean)


# @@protoc_insertion_point(module_scope)
