# This file was automatically generated by sub\epyqlib\epyqlib\cli\generateversion.py
__version_build_time__ = '2019-05-15T17:48:46.836856'

__version__ = '2019.5.3'
__sha__ = '898b7edfaf125ed0f63f523c4c4e30c0257b6cc2'
__revision__ = '898b7edfaf125ed0f63f523c4c4e30c0257b6cc2'
