
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-05-06T17:10:55-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "720d194e569d1727c46404a9ce1657c3f91c80a8",
 "version": "0.1.91"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
