
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-05-17T23:35:29-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "4dbfc2cc0cd3bb5ed2fe57821203a04cf51b0ac0",
 "version": "2019.5.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
