
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-05-10T08:52:41-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "90a0d37ec7a9407c45b6ce97c272bb7db9267dfa",
 "version": "v0.4.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
