# coding: utf-8

"""
    Doc Converter API

    This api converts file formats of OpenXml and OpenOffice documents formats to vector files (e.g., svg)  # noqa: E501

    OpenAPI spec version: 0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import presalytics_doc_converter
from presalytics_doc_converter.models.inline_object import InlineObject  # noqa: E501
from presalytics_doc_converter.rest import ApiException


class TestInlineObject(unittest.TestCase):
    """InlineObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineObject(self):
        """Test InlineObject"""
        # FIXME: construct object with mandatory attributes with example values
        # model = presalytics_doc_converter.models.inline_object.InlineObject()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
