
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-05-02T21:28:37+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "3a207b9da9169b784e9bfd53b3c81d3c90e15332",
 "version": "2019.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
