# coding: utf-8

"""
    Doc Converter API

    This api converts file formats of OpenXml and OpenOffice documents formats to vector files (e.g., svg)  # noqa: E501

    OpenAPI spec version: 0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import presalytics_doc_converter
from presalytics_doc_converter.api.default_api import DefaultApi  # noqa: E501
from presalytics_doc_converter.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = presalytics_doc_converter.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_root_get(self):
        """Test case for root_get

        """
        pass

    def test_svgconvert_post(self):
        """Test case for svgconvert_post

        converts pptx file to svg image  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
