MICROSOFT_AUTH_CLIENT_ID = "0d3fe9f6-95e8-4062-9a18-60294ab0b734"
MICROSOFT_AUTH_CLIENT_SECRET = "owlXYLK5!|cuprVQN8246]["

# MICROSOFT_AUTH_REGISTER_INACTIVE_ADMIN = True
# MICROSOFT_AUTH_LOGIN_TYPE = "xbl"
# MICROSOFT_AUTH_AUTO_MIGRATE_OPENID = True

# MICROSOFT_AUTH_TOKEN_HOOK = "microsoft_auth.conf"
