# -*- coding: utf-8 -*-

"""
    apimaticcicddemov10

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

from apimaticcicddemov10.decorators import lazy_property
from apimaticcicddemov10.configuration import Configuration
from apimaticcicddemov10.controllers.simple_calculator_controller import SimpleCalculatorController


class Apimaticcicddemov10Client(object):

    config = Configuration

    @lazy_property
    def simple_calculator(self):
        return SimpleCalculatorController()


