
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-05-20T20:28:16-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "2ef2bd97a8fc7a00ce074767815eb8fb71b5e8b8",
 "version": "4.2.10b1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
