TYPE_BOOL = 'BOOLEAN'
TYPE_DATE = 'DATE'
TYPE_STR = 'STRING'
TYPE_NUM = 'NUMERIC'

TYPE_CONST = 'CONSTANT'
TYPE_EMPTY = 'EMPTY'
TYPE_GEO = 'GEOMETRY'
TYPE_UNIQUE = 'UNIQUE'
TYPE_UNSUPPORTED = 'UNSUPPORTED'

SLIVER_AREA = 1
SLIVER_LINE = 1
