
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "468e6cf30e20530e461723e58e83ba39952284fb",
 "version": "1.9.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
