# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/piotrkowalczuk/charon/pb/rpc/charond/v1/permission.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from github.com.piotrkowalczuk.charon.pb.rpc.charond.v1 import common_pb2 as github_dot_com_dot_piotrkowalczuk_dot_charon_dot_pb_dot_rpc_dot_charond_dot_v1_dot_common__pb2
from qtypes import qtypes_pb2 as qtypes_dot_qtypes__pb2
from ntypes import ntypes_pb2 as ntypes_dot_ntypes__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='github.com/piotrkowalczuk/charon/pb/rpc/charond/v1/permission.proto',
  package='charon.rpc.charond.v1',
  syntax='proto3',
  serialized_options=_b('\n com.github.charon.rpc.charond.v1P\001Z:github.com/piotrkowalczuk/charon/pb/rpc/charond/v1;charond'),
  serialized_pb=_b('\nCgithub.com/piotrkowalczuk/charon/pb/rpc/charond/v1/permission.proto\x12\x15\x63haron.rpc.charond.v1\x1a?github.com/piotrkowalczuk/charon/pb/rpc/charond/v1/common.proto\x1a\x13qtypes/qtypes.proto\x1a\x13ntypes/ntypes.proto\"1\n\x1aRegisterPermissionsRequest\x12\x13\n\x0bpermissions\x18\x01 \x03(\t\"R\n\x1bRegisterPermissionsResponse\x12\x0f\n\x07\x63reated\x18\x01 \x01(\x03\x12\x0f\n\x07removed\x18\x02 \x01(\x03\x12\x11\n\tuntouched\x18\x03 \x01(\x03\"\xb0\x03\n\x16ListPermissionsRequest\x12!\n\tsubsystem\x18\x01 \x01(\x0b\x32\x0e.qtypes.String\x12\x1e\n\x06module\x18\x02 \x01(\x0b\x32\x0e.qtypes.String\x12\x1e\n\x06\x61\x63tion\x18\x03 \x01(\x0b\x32\x0e.qtypes.String\x12%\n\ncreated_at\x18\x04 \x01(\x0b\x32\x11.qtypes.Timestamp\x12!\n\ncreated_by\x18\x05 \x01(\x0b\x32\r.qtypes.Int64\x12\x1d\n\x06offset\x18\x64 \x01(\x0b\x32\r.ntypes.Int64\x12\x1c\n\x05limit\x18\x65 \x01(\x0b\x32\r.ntypes.Int64\x12I\n\x04sort\x18\x66 \x03(\x0b\x32\x37.charon.rpc.charond.v1.ListPermissionsRequest.SortEntryB\x02\x18\x01\x12.\n\x08order_by\x18g \x03(\x0b\x32\x1c.charon.rpc.charond.v1.Order\x1a+\n\tSortEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x08:\x02\x38\x01J\x04\x08\x06\x10\x64\".\n\x17ListPermissionsResponse\x12\x13\n\x0bpermissions\x18\x01 \x03(\t\"\"\n\x14GetPermissionRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"+\n\x15GetPermissionResponse\x12\x12\n\npermission\x18\x01 \x01(\t2\xd5\x02\n\x11PermissionManager\x12s\n\x08Register\x12\x31.charon.rpc.charond.v1.RegisterPermissionsRequest\x1a\x32.charon.rpc.charond.v1.RegisterPermissionsResponse\"\x00\x12g\n\x04List\x12-.charon.rpc.charond.v1.ListPermissionsRequest\x1a..charon.rpc.charond.v1.ListPermissionsResponse\"\x00\x12\x62\n\x03Get\x12+.charon.rpc.charond.v1.GetPermissionRequest\x1a,.charon.rpc.charond.v1.GetPermissionResponse\"\x00\x42`\n com.github.charon.rpc.charond.v1P\x01Z:github.com/piotrkowalczuk/charon/pb/rpc/charond/v1;charondb\x06proto3')
  ,
  dependencies=[github_dot_com_dot_piotrkowalczuk_dot_charon_dot_pb_dot_rpc_dot_charond_dot_v1_dot_common__pb2.DESCRIPTOR,qtypes_dot_qtypes__pb2.DESCRIPTOR,ntypes_dot_ntypes__pb2.DESCRIPTOR,])




_REGISTERPERMISSIONSREQUEST = _descriptor.Descriptor(
  name='RegisterPermissionsRequest',
  full_name='charon.rpc.charond.v1.RegisterPermissionsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='permissions', full_name='charon.rpc.charond.v1.RegisterPermissionsRequest.permissions', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=250,
)


_REGISTERPERMISSIONSRESPONSE = _descriptor.Descriptor(
  name='RegisterPermissionsResponse',
  full_name='charon.rpc.charond.v1.RegisterPermissionsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='created', full_name='charon.rpc.charond.v1.RegisterPermissionsResponse.created', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='removed', full_name='charon.rpc.charond.v1.RegisterPermissionsResponse.removed', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='untouched', full_name='charon.rpc.charond.v1.RegisterPermissionsResponse.untouched', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=252,
  serialized_end=334,
)


_LISTPERMISSIONSREQUEST_SORTENTRY = _descriptor.Descriptor(
  name='SortEntry',
  full_name='charon.rpc.charond.v1.ListPermissionsRequest.SortEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='charon.rpc.charond.v1.ListPermissionsRequest.SortEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='charon.rpc.charond.v1.ListPermissionsRequest.SortEntry.value', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=720,
  serialized_end=763,
)

_LISTPERMISSIONSREQUEST = _descriptor.Descriptor(
  name='ListPermissionsRequest',
  full_name='charon.rpc.charond.v1.ListPermissionsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='subsystem', full_name='charon.rpc.charond.v1.ListPermissionsRequest.subsystem', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='module', full_name='charon.rpc.charond.v1.ListPermissionsRequest.module', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action', full_name='charon.rpc.charond.v1.ListPermissionsRequest.action', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='created_at', full_name='charon.rpc.charond.v1.ListPermissionsRequest.created_at', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='created_by', full_name='charon.rpc.charond.v1.ListPermissionsRequest.created_by', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offset', full_name='charon.rpc.charond.v1.ListPermissionsRequest.offset', index=5,
      number=100, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='limit', full_name='charon.rpc.charond.v1.ListPermissionsRequest.limit', index=6,
      number=101, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sort', full_name='charon.rpc.charond.v1.ListPermissionsRequest.sort', index=7,
      number=102, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\030\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='order_by', full_name='charon.rpc.charond.v1.ListPermissionsRequest.order_by', index=8,
      number=103, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_LISTPERMISSIONSREQUEST_SORTENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=337,
  serialized_end=769,
)


_LISTPERMISSIONSRESPONSE = _descriptor.Descriptor(
  name='ListPermissionsResponse',
  full_name='charon.rpc.charond.v1.ListPermissionsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='permissions', full_name='charon.rpc.charond.v1.ListPermissionsResponse.permissions', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=771,
  serialized_end=817,
)


_GETPERMISSIONREQUEST = _descriptor.Descriptor(
  name='GetPermissionRequest',
  full_name='charon.rpc.charond.v1.GetPermissionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='charon.rpc.charond.v1.GetPermissionRequest.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=819,
  serialized_end=853,
)


_GETPERMISSIONRESPONSE = _descriptor.Descriptor(
  name='GetPermissionResponse',
  full_name='charon.rpc.charond.v1.GetPermissionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='permission', full_name='charon.rpc.charond.v1.GetPermissionResponse.permission', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=855,
  serialized_end=898,
)

_LISTPERMISSIONSREQUEST_SORTENTRY.containing_type = _LISTPERMISSIONSREQUEST
_LISTPERMISSIONSREQUEST.fields_by_name['subsystem'].message_type = qtypes_dot_qtypes__pb2._STRING
_LISTPERMISSIONSREQUEST.fields_by_name['module'].message_type = qtypes_dot_qtypes__pb2._STRING
_LISTPERMISSIONSREQUEST.fields_by_name['action'].message_type = qtypes_dot_qtypes__pb2._STRING
_LISTPERMISSIONSREQUEST.fields_by_name['created_at'].message_type = qtypes_dot_qtypes__pb2._TIMESTAMP
_LISTPERMISSIONSREQUEST.fields_by_name['created_by'].message_type = qtypes_dot_qtypes__pb2._INT64
_LISTPERMISSIONSREQUEST.fields_by_name['offset'].message_type = ntypes_dot_ntypes__pb2._INT64
_LISTPERMISSIONSREQUEST.fields_by_name['limit'].message_type = ntypes_dot_ntypes__pb2._INT64
_LISTPERMISSIONSREQUEST.fields_by_name['sort'].message_type = _LISTPERMISSIONSREQUEST_SORTENTRY
_LISTPERMISSIONSREQUEST.fields_by_name['order_by'].message_type = github_dot_com_dot_piotrkowalczuk_dot_charon_dot_pb_dot_rpc_dot_charond_dot_v1_dot_common__pb2._ORDER
DESCRIPTOR.message_types_by_name['RegisterPermissionsRequest'] = _REGISTERPERMISSIONSREQUEST
DESCRIPTOR.message_types_by_name['RegisterPermissionsResponse'] = _REGISTERPERMISSIONSRESPONSE
DESCRIPTOR.message_types_by_name['ListPermissionsRequest'] = _LISTPERMISSIONSREQUEST
DESCRIPTOR.message_types_by_name['ListPermissionsResponse'] = _LISTPERMISSIONSRESPONSE
DESCRIPTOR.message_types_by_name['GetPermissionRequest'] = _GETPERMISSIONREQUEST
DESCRIPTOR.message_types_by_name['GetPermissionResponse'] = _GETPERMISSIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RegisterPermissionsRequest = _reflection.GeneratedProtocolMessageType('RegisterPermissionsRequest', (_message.Message,), dict(
  DESCRIPTOR = _REGISTERPERMISSIONSREQUEST,
  __module__ = 'github.com.piotrkowalczuk.charon.pb.rpc.charond.v1.permission_pb2'
  # @@protoc_insertion_point(class_scope:charon.rpc.charond.v1.RegisterPermissionsRequest)
  ))
_sym_db.RegisterMessage(RegisterPermissionsRequest)

RegisterPermissionsResponse = _reflection.GeneratedProtocolMessageType('RegisterPermissionsResponse', (_message.Message,), dict(
  DESCRIPTOR = _REGISTERPERMISSIONSRESPONSE,
  __module__ = 'github.com.piotrkowalczuk.charon.pb.rpc.charond.v1.permission_pb2'
  # @@protoc_insertion_point(class_scope:charon.rpc.charond.v1.RegisterPermissionsResponse)
  ))
_sym_db.RegisterMessage(RegisterPermissionsResponse)

ListPermissionsRequest = _reflection.GeneratedProtocolMessageType('ListPermissionsRequest', (_message.Message,), dict(

  SortEntry = _reflection.GeneratedProtocolMessageType('SortEntry', (_message.Message,), dict(
    DESCRIPTOR = _LISTPERMISSIONSREQUEST_SORTENTRY,
    __module__ = 'github.com.piotrkowalczuk.charon.pb.rpc.charond.v1.permission_pb2'
    # @@protoc_insertion_point(class_scope:charon.rpc.charond.v1.ListPermissionsRequest.SortEntry)
    ))
  ,
  DESCRIPTOR = _LISTPERMISSIONSREQUEST,
  __module__ = 'github.com.piotrkowalczuk.charon.pb.rpc.charond.v1.permission_pb2'
  # @@protoc_insertion_point(class_scope:charon.rpc.charond.v1.ListPermissionsRequest)
  ))
_sym_db.RegisterMessage(ListPermissionsRequest)
_sym_db.RegisterMessage(ListPermissionsRequest.SortEntry)

ListPermissionsResponse = _reflection.GeneratedProtocolMessageType('ListPermissionsResponse', (_message.Message,), dict(
  DESCRIPTOR = _LISTPERMISSIONSRESPONSE,
  __module__ = 'github.com.piotrkowalczuk.charon.pb.rpc.charond.v1.permission_pb2'
  # @@protoc_insertion_point(class_scope:charon.rpc.charond.v1.ListPermissionsResponse)
  ))
_sym_db.RegisterMessage(ListPermissionsResponse)

GetPermissionRequest = _reflection.GeneratedProtocolMessageType('GetPermissionRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETPERMISSIONREQUEST,
  __module__ = 'github.com.piotrkowalczuk.charon.pb.rpc.charond.v1.permission_pb2'
  # @@protoc_insertion_point(class_scope:charon.rpc.charond.v1.GetPermissionRequest)
  ))
_sym_db.RegisterMessage(GetPermissionRequest)

GetPermissionResponse = _reflection.GeneratedProtocolMessageType('GetPermissionResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETPERMISSIONRESPONSE,
  __module__ = 'github.com.piotrkowalczuk.charon.pb.rpc.charond.v1.permission_pb2'
  # @@protoc_insertion_point(class_scope:charon.rpc.charond.v1.GetPermissionResponse)
  ))
_sym_db.RegisterMessage(GetPermissionResponse)


DESCRIPTOR._options = None
_LISTPERMISSIONSREQUEST_SORTENTRY._options = None
_LISTPERMISSIONSREQUEST.fields_by_name['sort']._options = None

_PERMISSIONMANAGER = _descriptor.ServiceDescriptor(
  name='PermissionManager',
  full_name='charon.rpc.charond.v1.PermissionManager',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=901,
  serialized_end=1242,
  methods=[
  _descriptor.MethodDescriptor(
    name='Register',
    full_name='charon.rpc.charond.v1.PermissionManager.Register',
    index=0,
    containing_service=None,
    input_type=_REGISTERPERMISSIONSREQUEST,
    output_type=_REGISTERPERMISSIONSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='List',
    full_name='charon.rpc.charond.v1.PermissionManager.List',
    index=1,
    containing_service=None,
    input_type=_LISTPERMISSIONSREQUEST,
    output_type=_LISTPERMISSIONSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Get',
    full_name='charon.rpc.charond.v1.PermissionManager.Get',
    index=2,
    containing_service=None,
    input_type=_GETPERMISSIONREQUEST,
    output_type=_GETPERMISSIONRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PERMISSIONMANAGER)

DESCRIPTOR.services_by_name['PermissionManager'] = _PERMISSIONMANAGER

# @@protoc_insertion_point(module_scope)
