
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-05-10T16:31:20-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "60eb32b6e43eada1c8fc0048fafef244c16cbe11",
 "version": "0.2.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
