# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (3, 0, 0):
    new_instancemethod = lambda func, inst, cls: _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.SWIG_PyInstanceMethod_New(func)
else:
    from new import instancemethod as new_instancemethod
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_rtkSimplexSpectralProjectionsDecompositionImageFilterPython', [dirname(__file__)])
        except ImportError:
            import _rtkSimplexSpectralProjectionsDecompositionImageFilterPython
            return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython
        if fp is not None:
            try:
                _mod = imp.load_module('_rtkSimplexSpectralProjectionsDecompositionImageFilterPython', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _rtkSimplexSpectralProjectionsDecompositionImageFilterPython = swig_import_helper()
    del swig_import_helper
else:
    import _rtkSimplexSpectralProjectionsDecompositionImageFilterPython
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



def _swig_setattr_nondynamic_method(set):
    def set_attr(self, name, value):
        if (name == "thisown"):
            return self.this.own(value)
        if hasattr(self, name) or (name == "this"):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr


import itkVectorImageRTKPython
import itkVectorImagePython
import itkVariableLengthVectorPython
import stdcomplexPython
import pyBasePython
import itkImagePython
import itkOffsetPython
import itkSizePython
import itkMatrixPython
import vnl_matrixPython
import vnl_vectorPython
import vnl_matrix_fixedPython
import itkPointPython
import vnl_vector_refPython
import itkFixedArrayPython
import itkVectorPython
import itkCovariantVectorPython
import ITKCommonBasePython
import itkSymmetricSecondRankTensorPython
import itkIndexPython
import itkRGBPixelPython
import itkImageRegionPython
import itkRGBAPixelPython
import itkImageRTKPython
import itkImageBaseRTKPython
import itkMatrixRTKPython
import itkPointRTKPython
import itkCovariantVectorRTKPython
import itkImageRegionRTKPython
import itkImageToImageFilterAPython
import itkImageSourcePython
import itkImageSourceCommonPython
import itkImageToImageFilterCommonPython

def rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_New():
  return rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2.New()

class rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2(itkImageToImageFilterAPython.itkImageToImageFilterVIF3VIF3):
    """Proxy of C++ rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2 class."""

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__() -> "rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_Pointer":
        """__New_orig__() -> rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_Pointer"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self) -> "rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_Pointer":
        """Clone(rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2 self) -> rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_Pointer"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_Clone(self)


    def SetInputDecomposedProjections(self, DecomposedProjections: 'itkVectorImageF3') -> "void":
        """SetInputDecomposedProjections(rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2 self, itkVectorImageF3 DecomposedProjections)"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_SetInputDecomposedProjections(self, DecomposedProjections)


    def GetInputDecomposedProjections(self) -> "itkVectorImageF3_ConstPointer":
        """GetInputDecomposedProjections(rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2 self) -> itkVectorImageF3_ConstPointer"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_GetInputDecomposedProjections(self)


    def SetInputMeasuredProjections(self, SpectralProjections: 'itkVectorImageF3') -> "void":
        """SetInputMeasuredProjections(rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2 self, itkVectorImageF3 SpectralProjections)"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_SetInputMeasuredProjections(self, SpectralProjections)


    def GetInputMeasuredProjections(self) -> "itkVectorImageF3_ConstPointer":
        """GetInputMeasuredProjections(rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2 self) -> itkVectorImageF3_ConstPointer"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_GetInputMeasuredProjections(self)


    def SetDetectorResponse(self, DetectorResponse: 'itkImageF2') -> "void":
        """SetDetectorResponse(rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2 self, itkImageF2 DetectorResponse)"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_SetDetectorResponse(self, DetectorResponse)


    def GetDetectorResponse(self) -> "itkImageF2_ConstPointer":
        """GetDetectorResponse(rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2 self) -> itkImageF2_ConstPointer"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_GetDetectorResponse(self)


    def SetMaterialAttenuations(self, MaterialAttenuations: 'itkImageF2') -> "void":
        """SetMaterialAttenuations(rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2 self, itkImageF2 MaterialAttenuations)"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_SetMaterialAttenuations(self, MaterialAttenuations)


    def GetMaterialAttenuations(self) -> "itkImageF2_ConstPointer":
        """GetMaterialAttenuations(rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2 self) -> itkImageF2_ConstPointer"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_GetMaterialAttenuations(self)


    def SetInputIncidentSpectrum(self, IncidentSpectrum: 'itkVectorImageF2') -> "void":
        """SetInputIncidentSpectrum(rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2 self, itkVectorImageF2 IncidentSpectrum)"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_SetInputIncidentSpectrum(self, IncidentSpectrum)


    def SetInputSecondIncidentSpectrum(self, IncidentSpectrum: 'itkVectorImageF2') -> "void":
        """SetInputSecondIncidentSpectrum(rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2 self, itkVectorImageF2 IncidentSpectrum)"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_SetInputSecondIncidentSpectrum(self, IncidentSpectrum)


    def GetInputIncidentSpectrum(self) -> "itkVectorImageF2_ConstPointer":
        """GetInputIncidentSpectrum(rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2 self) -> itkVectorImageF2_ConstPointer"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_GetInputIncidentSpectrum(self)


    def GetInputSecondIncidentSpectrum(self) -> "itkVectorImageF2_ConstPointer":
        """GetInputSecondIncidentSpectrum(rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2 self) -> itkVectorImageF2_ConstPointer"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_GetInputSecondIncidentSpectrum(self)


    def GetNumberOfIterations(self) -> "unsigned int":
        """GetNumberOfIterations(rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2 self) -> unsigned int"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_GetNumberOfIterations(self)


    def SetNumberOfIterations(self, _arg: 'unsigned int const') -> "void":
        """SetNumberOfIterations(rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2 self, unsigned int const _arg)"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_SetNumberOfIterations(self, _arg)


    def SetNumberOfEnergies(self, _arg: 'unsigned int const') -> "void":
        """SetNumberOfEnergies(rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2 self, unsigned int const _arg)"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_SetNumberOfEnergies(self, _arg)


    def GetNumberOfEnergies(self) -> "unsigned int":
        """GetNumberOfEnergies(rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2 self) -> unsigned int"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_GetNumberOfEnergies(self)


    def SetNumberOfMaterials(self, _arg: 'unsigned int const') -> "void":
        """SetNumberOfMaterials(rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2 self, unsigned int const _arg)"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_SetNumberOfMaterials(self, _arg)


    def GetNumberOfMaterials(self) -> "unsigned int":
        """GetNumberOfMaterials(rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2 self) -> unsigned int"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_GetNumberOfMaterials(self)


    def SetOptimizeWithRestarts(self, _arg: 'bool const') -> "void":
        """SetOptimizeWithRestarts(rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2 self, bool const _arg)"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_SetOptimizeWithRestarts(self, _arg)


    def GetOptimizeWithRestarts(self) -> "bool":
        """GetOptimizeWithRestarts(rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2 self) -> bool"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_GetOptimizeWithRestarts(self)


    def SetThresholds(self, _arg: 'itkVariableLengthVectorD') -> "void":
        """SetThresholds(rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2 self, itkVariableLengthVectorD _arg)"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_SetThresholds(self, _arg)


    def GetThresholds(self) -> "itkVariableLengthVectorD":
        """GetThresholds(rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2 self) -> itkVariableLengthVectorD"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_GetThresholds(self)


    def SetNumberOfSpectralBins(self, _arg: 'unsigned int const') -> "void":
        """SetNumberOfSpectralBins(rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2 self, unsigned int const _arg)"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_SetNumberOfSpectralBins(self, _arg)


    def GetNumberOfSpectralBins(self) -> "unsigned int":
        """GetNumberOfSpectralBins(rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2 self) -> unsigned int"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_GetNumberOfSpectralBins(self)


    def SetOutputInverseCramerRaoLowerBound(self, _arg: 'bool const') -> "void":
        """SetOutputInverseCramerRaoLowerBound(rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2 self, bool const _arg)"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_SetOutputInverseCramerRaoLowerBound(self, _arg)


    def GetOutputInverseCramerRaoLowerBound(self) -> "bool":
        """GetOutputInverseCramerRaoLowerBound(rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2 self) -> bool"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_GetOutputInverseCramerRaoLowerBound(self)


    def SetOutputFischerMatrix(self, _arg: 'bool const') -> "void":
        """SetOutputFischerMatrix(rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2 self, bool const _arg)"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_SetOutputFischerMatrix(self, _arg)


    def GetOutputFischerMatrix(self) -> "bool":
        """GetOutputFischerMatrix(rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2 self) -> bool"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_GetOutputFischerMatrix(self)


    def SetLogTransformEachBin(self, _arg: 'bool const') -> "void":
        """SetLogTransformEachBin(rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2 self, bool const _arg)"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_SetLogTransformEachBin(self, _arg)


    def GetLogTransformEachBin(self) -> "bool":
        """GetLogTransformEachBin(rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2 self) -> bool"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_GetLogTransformEachBin(self)


    def SetGuessInitialization(self, _arg: 'bool const') -> "void":
        """SetGuessInitialization(rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2 self, bool const _arg)"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_SetGuessInitialization(self, _arg)


    def GetGuessInitialization(self) -> "bool":
        """GetGuessInitialization(rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2 self) -> bool"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_GetGuessInitialization(self)


    def SetIsSpectralCT(self, _arg: 'bool const') -> "void":
        """SetIsSpectralCT(rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2 self, bool const _arg)"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_SetIsSpectralCT(self, _arg)


    def GetIsSpectralCT(self) -> "bool":
        """GetIsSpectralCT(rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2 self) -> bool"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_GetIsSpectralCT(self)

    __swig_destroy__ = _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.delete_rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2

    def cast(obj: 'itkLightObject') -> "rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2 *":
        """cast(itkLightObject obj) -> rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_cast(obj)

    cast = staticmethod(cast)

    def New(*args, **kargs):
        """New() -> rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2

        Create a new object of the class rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2.Clone = new_instancemethod(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_Clone, None, rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2)
rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2.SetInputDecomposedProjections = new_instancemethod(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_SetInputDecomposedProjections, None, rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2)
rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2.GetInputDecomposedProjections = new_instancemethod(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_GetInputDecomposedProjections, None, rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2)
rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2.SetInputMeasuredProjections = new_instancemethod(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_SetInputMeasuredProjections, None, rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2)
rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2.GetInputMeasuredProjections = new_instancemethod(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_GetInputMeasuredProjections, None, rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2)
rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2.SetDetectorResponse = new_instancemethod(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_SetDetectorResponse, None, rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2)
rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2.GetDetectorResponse = new_instancemethod(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_GetDetectorResponse, None, rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2)
rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2.SetMaterialAttenuations = new_instancemethod(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_SetMaterialAttenuations, None, rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2)
rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2.GetMaterialAttenuations = new_instancemethod(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_GetMaterialAttenuations, None, rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2)
rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2.SetInputIncidentSpectrum = new_instancemethod(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_SetInputIncidentSpectrum, None, rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2)
rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2.SetInputSecondIncidentSpectrum = new_instancemethod(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_SetInputSecondIncidentSpectrum, None, rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2)
rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2.GetInputIncidentSpectrum = new_instancemethod(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_GetInputIncidentSpectrum, None, rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2)
rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2.GetInputSecondIncidentSpectrum = new_instancemethod(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_GetInputSecondIncidentSpectrum, None, rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2)
rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2.GetNumberOfIterations = new_instancemethod(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_GetNumberOfIterations, None, rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2)
rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2.SetNumberOfIterations = new_instancemethod(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_SetNumberOfIterations, None, rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2)
rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2.SetNumberOfEnergies = new_instancemethod(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_SetNumberOfEnergies, None, rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2)
rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2.GetNumberOfEnergies = new_instancemethod(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_GetNumberOfEnergies, None, rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2)
rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2.SetNumberOfMaterials = new_instancemethod(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_SetNumberOfMaterials, None, rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2)
rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2.GetNumberOfMaterials = new_instancemethod(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_GetNumberOfMaterials, None, rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2)
rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2.SetOptimizeWithRestarts = new_instancemethod(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_SetOptimizeWithRestarts, None, rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2)
rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2.GetOptimizeWithRestarts = new_instancemethod(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_GetOptimizeWithRestarts, None, rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2)
rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2.SetThresholds = new_instancemethod(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_SetThresholds, None, rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2)
rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2.GetThresholds = new_instancemethod(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_GetThresholds, None, rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2)
rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2.SetNumberOfSpectralBins = new_instancemethod(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_SetNumberOfSpectralBins, None, rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2)
rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2.GetNumberOfSpectralBins = new_instancemethod(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_GetNumberOfSpectralBins, None, rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2)
rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2.SetOutputInverseCramerRaoLowerBound = new_instancemethod(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_SetOutputInverseCramerRaoLowerBound, None, rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2)
rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2.GetOutputInverseCramerRaoLowerBound = new_instancemethod(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_GetOutputInverseCramerRaoLowerBound, None, rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2)
rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2.SetOutputFischerMatrix = new_instancemethod(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_SetOutputFischerMatrix, None, rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2)
rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2.GetOutputFischerMatrix = new_instancemethod(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_GetOutputFischerMatrix, None, rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2)
rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2.SetLogTransformEachBin = new_instancemethod(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_SetLogTransformEachBin, None, rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2)
rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2.GetLogTransformEachBin = new_instancemethod(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_GetLogTransformEachBin, None, rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2)
rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2.SetGuessInitialization = new_instancemethod(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_SetGuessInitialization, None, rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2)
rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2.GetGuessInitialization = new_instancemethod(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_GetGuessInitialization, None, rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2)
rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2.SetIsSpectralCT = new_instancemethod(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_SetIsSpectralCT, None, rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2)
rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2.GetIsSpectralCT = new_instancemethod(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_GetIsSpectralCT, None, rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2)
rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_swigregister = _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_swigregister
rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_swigregister(rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2)

def rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2___New_orig__() -> "rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_Pointer":
    """rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2___New_orig__() -> rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_Pointer"""
    return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2___New_orig__()

def rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_cast(obj: 'itkLightObject') -> "rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2 *":
    """rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_cast(itkLightObject obj) -> rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2"""
    return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_cast(obj)


def simplex_spectral_projections_decomposition_image_filter(*args, **kwargs):
    """Procedural interface for SimplexSpectralProjectionsDecompositionImageFilter"""
    import itk
    instance = itk.SimplexSpectralProjectionsDecompositionImageFilter.New(*args, **kwargs)
    return instance.__internal_call__()

def simplex_spectral_projections_decomposition_image_filter_init_docstring():
    import itk
    import itkTemplate
    if isinstance(itk.SimplexSpectralProjectionsDecompositionImageFilter, itkTemplate.itkTemplate):
        simplex_spectral_projections_decomposition_image_filter.__doc__ = itk.SimplexSpectralProjectionsDecompositionImageFilter.values()[0].__doc__
    else:
        simplex_spectral_projections_decomposition_image_filter.__doc__ = itk.SimplexSpectralProjectionsDecompositionImageFilter.__doc__




