# This file was automatically generated by sub\epyqlib\epyqlib\cli\generateversion.py
__version_build_time__ = '2019-05-10T20:07:39.636432'

__version__ = '2019.5.2'
__sha__ = 'bb8916c01f6ad62d6c9501f63d4358a0c2d0deff'
__revision__ = 'bb8916c01f6ad62d6c9501f63d4358a0c2d0deff'
