# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (3, 0, 0):
    new_instancemethod = lambda func, inst, cls: _rtkPolynomialGainCorrectionImageFilterPython.SWIG_PyInstanceMethod_New(func)
else:
    from new import instancemethod as new_instancemethod
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_rtkPolynomialGainCorrectionImageFilterPython', [dirname(__file__)])
        except ImportError:
            import _rtkPolynomialGainCorrectionImageFilterPython
            return _rtkPolynomialGainCorrectionImageFilterPython
        if fp is not None:
            try:
                _mod = imp.load_module('_rtkPolynomialGainCorrectionImageFilterPython', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _rtkPolynomialGainCorrectionImageFilterPython = swig_import_helper()
    del swig_import_helper
else:
    import _rtkPolynomialGainCorrectionImageFilterPython
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



def _swig_setattr_nondynamic_method(set):
    def set_attr(self, name, value):
        if (name == "thisown"):
            return self.this.own(value)
        if hasattr(self, name) or (name == "this"):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr


import itkImageRegionPython
import itkSizePython
import pyBasePython
import itkIndexPython
import itkOffsetPython
import ITKCommonBasePython
import itkImagePython
import stdcomplexPython
import itkPointPython
import itkFixedArrayPython
import vnl_vectorPython
import vnl_matrixPython
import vnl_vector_refPython
import itkVectorPython
import itkRGBAPixelPython
import itkSymmetricSecondRankTensorPython
import itkMatrixPython
import vnl_matrix_fixedPython
import itkCovariantVectorPython
import itkRGBPixelPython
import itkImageToImageFilterAPython
import itkVectorImagePython
import itkVariableLengthVectorPython
import itkImageSourcePython
import itkImageSourceCommonPython
import itkImageToImageFilterCommonPython

def rtkPolynomialGainCorrectionImageFilterIF3IF3_New():
  return rtkPolynomialGainCorrectionImageFilterIF3IF3.New()

class rtkPolynomialGainCorrectionImageFilterIF3IF3(itkImageToImageFilterAPython.itkImageToImageFilterIF3IF3):
    """Proxy of C++ rtkPolynomialGainCorrectionImageFilterIF3IF3 class."""

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__() -> "rtkPolynomialGainCorrectionImageFilterIF3IF3_Pointer":
        """__New_orig__() -> rtkPolynomialGainCorrectionImageFilterIF3IF3_Pointer"""
        return _rtkPolynomialGainCorrectionImageFilterPython.rtkPolynomialGainCorrectionImageFilterIF3IF3___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self) -> "rtkPolynomialGainCorrectionImageFilterIF3IF3_Pointer":
        """Clone(rtkPolynomialGainCorrectionImageFilterIF3IF3 self) -> rtkPolynomialGainCorrectionImageFilterIF3IF3_Pointer"""
        return _rtkPolynomialGainCorrectionImageFilterPython.rtkPolynomialGainCorrectionImageFilterIF3IF3_Clone(self)


    def SetDarkImage(self, gain: 'itkImageF3_Pointer const') -> "void":
        """SetDarkImage(rtkPolynomialGainCorrectionImageFilterIF3IF3 self, itkImageF3_Pointer const gain)"""
        return _rtkPolynomialGainCorrectionImageFilterPython.rtkPolynomialGainCorrectionImageFilterIF3IF3_SetDarkImage(self, gain)


    def SetGainCoefficients(self, gain: 'itkImageF3_Pointer const') -> "void":
        """SetGainCoefficients(rtkPolynomialGainCorrectionImageFilterIF3IF3 self, itkImageF3_Pointer const gain)"""
        return _rtkPolynomialGainCorrectionImageFilterPython.rtkPolynomialGainCorrectionImageFilterIF3IF3_SetGainCoefficients(self, gain)


    def SetK(self, _arg: 'float const') -> "void":
        """SetK(rtkPolynomialGainCorrectionImageFilterIF3IF3 self, float const _arg)"""
        return _rtkPolynomialGainCorrectionImageFilterPython.rtkPolynomialGainCorrectionImageFilterIF3IF3_SetK(self, _arg)


    def GetK(self) -> "float":
        """GetK(rtkPolynomialGainCorrectionImageFilterIF3IF3 self) -> float"""
        return _rtkPolynomialGainCorrectionImageFilterPython.rtkPolynomialGainCorrectionImageFilterIF3IF3_GetK(self)

    __swig_destroy__ = _rtkPolynomialGainCorrectionImageFilterPython.delete_rtkPolynomialGainCorrectionImageFilterIF3IF3

    def cast(obj: 'itkLightObject') -> "rtkPolynomialGainCorrectionImageFilterIF3IF3 *":
        """cast(itkLightObject obj) -> rtkPolynomialGainCorrectionImageFilterIF3IF3"""
        return _rtkPolynomialGainCorrectionImageFilterPython.rtkPolynomialGainCorrectionImageFilterIF3IF3_cast(obj)

    cast = staticmethod(cast)

    def New(*args, **kargs):
        """New() -> rtkPolynomialGainCorrectionImageFilterIF3IF3

        Create a new object of the class rtkPolynomialGainCorrectionImageFilterIF3IF3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          rtkPolynomialGainCorrectionImageFilterIF3IF3.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = rtkPolynomialGainCorrectionImageFilterIF3IF3.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = rtkPolynomialGainCorrectionImageFilterIF3IF3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

rtkPolynomialGainCorrectionImageFilterIF3IF3.Clone = new_instancemethod(_rtkPolynomialGainCorrectionImageFilterPython.rtkPolynomialGainCorrectionImageFilterIF3IF3_Clone, None, rtkPolynomialGainCorrectionImageFilterIF3IF3)
rtkPolynomialGainCorrectionImageFilterIF3IF3.SetDarkImage = new_instancemethod(_rtkPolynomialGainCorrectionImageFilterPython.rtkPolynomialGainCorrectionImageFilterIF3IF3_SetDarkImage, None, rtkPolynomialGainCorrectionImageFilterIF3IF3)
rtkPolynomialGainCorrectionImageFilterIF3IF3.SetGainCoefficients = new_instancemethod(_rtkPolynomialGainCorrectionImageFilterPython.rtkPolynomialGainCorrectionImageFilterIF3IF3_SetGainCoefficients, None, rtkPolynomialGainCorrectionImageFilterIF3IF3)
rtkPolynomialGainCorrectionImageFilterIF3IF3.SetK = new_instancemethod(_rtkPolynomialGainCorrectionImageFilterPython.rtkPolynomialGainCorrectionImageFilterIF3IF3_SetK, None, rtkPolynomialGainCorrectionImageFilterIF3IF3)
rtkPolynomialGainCorrectionImageFilterIF3IF3.GetK = new_instancemethod(_rtkPolynomialGainCorrectionImageFilterPython.rtkPolynomialGainCorrectionImageFilterIF3IF3_GetK, None, rtkPolynomialGainCorrectionImageFilterIF3IF3)
rtkPolynomialGainCorrectionImageFilterIF3IF3_swigregister = _rtkPolynomialGainCorrectionImageFilterPython.rtkPolynomialGainCorrectionImageFilterIF3IF3_swigregister
rtkPolynomialGainCorrectionImageFilterIF3IF3_swigregister(rtkPolynomialGainCorrectionImageFilterIF3IF3)

def rtkPolynomialGainCorrectionImageFilterIF3IF3___New_orig__() -> "rtkPolynomialGainCorrectionImageFilterIF3IF3_Pointer":
    """rtkPolynomialGainCorrectionImageFilterIF3IF3___New_orig__() -> rtkPolynomialGainCorrectionImageFilterIF3IF3_Pointer"""
    return _rtkPolynomialGainCorrectionImageFilterPython.rtkPolynomialGainCorrectionImageFilterIF3IF3___New_orig__()

def rtkPolynomialGainCorrectionImageFilterIF3IF3_cast(obj: 'itkLightObject') -> "rtkPolynomialGainCorrectionImageFilterIF3IF3 *":
    """rtkPolynomialGainCorrectionImageFilterIF3IF3_cast(itkLightObject obj) -> rtkPolynomialGainCorrectionImageFilterIF3IF3"""
    return _rtkPolynomialGainCorrectionImageFilterPython.rtkPolynomialGainCorrectionImageFilterIF3IF3_cast(obj)


def polynomial_gain_correction_image_filter(*args, **kwargs):
    """Procedural interface for PolynomialGainCorrectionImageFilter"""
    import itk
    instance = itk.PolynomialGainCorrectionImageFilter.New(*args, **kwargs)
    return instance.__internal_call__()

def polynomial_gain_correction_image_filter_init_docstring():
    import itk
    import itkTemplate
    if isinstance(itk.PolynomialGainCorrectionImageFilter, itkTemplate.itkTemplate):
        polynomial_gain_correction_image_filter.__doc__ = itk.PolynomialGainCorrectionImageFilter.values()[0].__doc__
    else:
        polynomial_gain_correction_image_filter.__doc__ = itk.PolynomialGainCorrectionImageFilter.__doc__




