# Generated by Django 2.1.7 on 2019-05-20 13:30

from django.db import migrations
import djangoplus.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0001_squashed_0006_auto_20170605_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=djangoplus.db.models.fields.CharField(max_length=255, verbose_name='Número'),
        ),
    ]
