# Generated by Django 2.2 on 2019-05-05 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_pays', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('order_id', models.CharField(max_length=10, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='amount')),
                ('pays_gateway', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_pays.Gateway')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='amount')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoapp.Order')),
                ('payment', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identified_order_payment', to='django_pays.Payment')),
            ],
            options={
                'verbose_name': 'order payment',
                'verbose_name_plural': 'order payments',
            },
        ),
    ]
