
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2019-05-14T08:24:09+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "9a6af1060cb087d201e842482b1dece317147cbb",
 "version": "2019.5.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
