
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-05-21T14:07:20-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "e4584773281c92df09c78c69722aea1dd085670c",
 "version": "0.1.0a6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
