
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "eb0ec379cc8e7a6d2f39d4b475aedea556226872",
 "version": "2137"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
