# coding: utf-8

"""
    Pulp 3 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v3
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from pulpcore.client.pulp_file.api_client import ApiClient
from pulpcore.client.pulp_file.exceptions import (
    ApiTypeError,
    ApiValueError
)


class PublishersApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def publishers_file_file_create(self, data, **kwargs):  # noqa: E501
        """Create a file publisher  # noqa: E501

        ViewSet for File Publishers.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.publishers_file_file_create(data, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param FilePublisher data: (required)
        :return: FilePublisher
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.publishers_file_file_create_with_http_info(data, **kwargs)  # noqa: E501
        else:
            (data) = self.publishers_file_file_create_with_http_info(data, **kwargs)  # noqa: E501
            return data

    def publishers_file_file_create_with_http_info(self, data, **kwargs):  # noqa: E501
        """Create a file publisher  # noqa: E501

        ViewSet for File Publishers.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.publishers_file_file_create_with_http_info(data, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param FilePublisher data: (required)
        :return: FilePublisher
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['data']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method publishers_file_file_create" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'data' is set
        if ('data' not in local_var_params or
                local_var_params['data'] is None):
            raise ApiValueError("Missing the required parameter `data` when calling `publishers_file_file_create`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'data' in local_var_params:
            body_params = local_var_params['data']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Basic']  # noqa: E501

        return self.api_client.call_api(
            '/pulp/api/v3/publishers/file/file/', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='FilePublisher',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def publishers_file_file_delete(self, file_publisher_href, **kwargs):  # noqa: E501
        """Delete a file publisher  # noqa: E501

        Trigger an asynchronous delete task  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.publishers_file_file_delete(file_publisher_href, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str file_publisher_href: URI of File Publisher. e.g.: /pulp/api/v3/publishers/file/file/1/ (required)
        :return: AsyncOperationResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.publishers_file_file_delete_with_http_info(file_publisher_href, **kwargs)  # noqa: E501
        else:
            (data) = self.publishers_file_file_delete_with_http_info(file_publisher_href, **kwargs)  # noqa: E501
            return data

    def publishers_file_file_delete_with_http_info(self, file_publisher_href, **kwargs):  # noqa: E501
        """Delete a file publisher  # noqa: E501

        Trigger an asynchronous delete task  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.publishers_file_file_delete_with_http_info(file_publisher_href, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str file_publisher_href: URI of File Publisher. e.g.: /pulp/api/v3/publishers/file/file/1/ (required)
        :return: AsyncOperationResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['file_publisher_href']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method publishers_file_file_delete" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'file_publisher_href' is set
        if ('file_publisher_href' not in local_var_params or
                local_var_params['file_publisher_href'] is None):
            raise ApiValueError("Missing the required parameter `file_publisher_href` when calling `publishers_file_file_delete`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'file_publisher_href' in local_var_params:
            path_params['file_publisher_href'] = local_var_params['file_publisher_href']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Basic']  # noqa: E501

        return self.api_client.call_api(
            '{file_publisher_href}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='AsyncOperationResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def publishers_file_file_list(self, **kwargs):  # noqa: E501
        """List file publishers  # noqa: E501

        ViewSet for File Publishers.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.publishers_file_file_list(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str name:
        :param str name__in: Filter results where name is in a comma-separated list of values
        :param str last_updated__lt: Filter results where _last_updated is less than value
        :param str last_updated__lte: Filter results where _last_updated is less than or equal to value
        :param str last_updated__gt: Filter results where _last_updated is greater than value
        :param str last_updated__gte: Filter results where _last_updated is greater than or equal to value
        :param str last_updated__range: Filter results where _last_updated is between two comma separated values
        :param str last_updated: ISO 8601 formatted dates are supported
        :param int page: A page number within the paginated result set.
        :param int page_size: Number of results to return per page.
        :return: InlineResponse2003
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.publishers_file_file_list_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.publishers_file_file_list_with_http_info(**kwargs)  # noqa: E501
            return data

    def publishers_file_file_list_with_http_info(self, **kwargs):  # noqa: E501
        """List file publishers  # noqa: E501

        ViewSet for File Publishers.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.publishers_file_file_list_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str name:
        :param str name__in: Filter results where name is in a comma-separated list of values
        :param str last_updated__lt: Filter results where _last_updated is less than value
        :param str last_updated__lte: Filter results where _last_updated is less than or equal to value
        :param str last_updated__gt: Filter results where _last_updated is greater than value
        :param str last_updated__gte: Filter results where _last_updated is greater than or equal to value
        :param str last_updated__range: Filter results where _last_updated is between two comma separated values
        :param str last_updated: ISO 8601 formatted dates are supported
        :param int page: A page number within the paginated result set.
        :param int page_size: Number of results to return per page.
        :return: InlineResponse2003
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['name', 'name__in', 'last_updated__lt', 'last_updated__lte', 'last_updated__gt', 'last_updated__gte', 'last_updated__range', 'last_updated', 'page', 'page_size']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method publishers_file_file_list" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'name' in local_var_params:
            query_params.append(('name', local_var_params['name']))  # noqa: E501
        if 'name__in' in local_var_params:
            query_params.append(('name__in', local_var_params['name__in']))  # noqa: E501
        if 'last_updated__lt' in local_var_params:
            query_params.append(('_last_updated__lt', local_var_params['last_updated__lt']))  # noqa: E501
        if 'last_updated__lte' in local_var_params:
            query_params.append(('_last_updated__lte', local_var_params['last_updated__lte']))  # noqa: E501
        if 'last_updated__gt' in local_var_params:
            query_params.append(('_last_updated__gt', local_var_params['last_updated__gt']))  # noqa: E501
        if 'last_updated__gte' in local_var_params:
            query_params.append(('_last_updated__gte', local_var_params['last_updated__gte']))  # noqa: E501
        if 'last_updated__range' in local_var_params:
            query_params.append(('_last_updated__range', local_var_params['last_updated__range']))  # noqa: E501
        if 'last_updated' in local_var_params:
            query_params.append(('_last_updated', local_var_params['last_updated']))  # noqa: E501
        if 'page' in local_var_params:
            query_params.append(('page', local_var_params['page']))  # noqa: E501
        if 'page_size' in local_var_params:
            query_params.append(('page_size', local_var_params['page_size']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Basic']  # noqa: E501

        return self.api_client.call_api(
            '/pulp/api/v3/publishers/file/file/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InlineResponse2003',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def publishers_file_file_partial_update(self, file_publisher_href, data, **kwargs):  # noqa: E501
        """Partially update a file publisher  # noqa: E501

        Trigger an asynchronous partial update task  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.publishers_file_file_partial_update(file_publisher_href, data, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str file_publisher_href: URI of File Publisher. e.g.: /pulp/api/v3/publishers/file/file/1/ (required)
        :param FilePublisher data: (required)
        :return: AsyncOperationResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.publishers_file_file_partial_update_with_http_info(file_publisher_href, data, **kwargs)  # noqa: E501
        else:
            (data) = self.publishers_file_file_partial_update_with_http_info(file_publisher_href, data, **kwargs)  # noqa: E501
            return data

    def publishers_file_file_partial_update_with_http_info(self, file_publisher_href, data, **kwargs):  # noqa: E501
        """Partially update a file publisher  # noqa: E501

        Trigger an asynchronous partial update task  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.publishers_file_file_partial_update_with_http_info(file_publisher_href, data, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str file_publisher_href: URI of File Publisher. e.g.: /pulp/api/v3/publishers/file/file/1/ (required)
        :param FilePublisher data: (required)
        :return: AsyncOperationResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['file_publisher_href', 'data']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method publishers_file_file_partial_update" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'file_publisher_href' is set
        if ('file_publisher_href' not in local_var_params or
                local_var_params['file_publisher_href'] is None):
            raise ApiValueError("Missing the required parameter `file_publisher_href` when calling `publishers_file_file_partial_update`")  # noqa: E501
        # verify the required parameter 'data' is set
        if ('data' not in local_var_params or
                local_var_params['data'] is None):
            raise ApiValueError("Missing the required parameter `data` when calling `publishers_file_file_partial_update`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'file_publisher_href' in local_var_params:
            path_params['file_publisher_href'] = local_var_params['file_publisher_href']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'data' in local_var_params:
            body_params = local_var_params['data']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Basic']  # noqa: E501

        return self.api_client.call_api(
            '{file_publisher_href}', 'PATCH',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='AsyncOperationResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def publishers_file_file_read(self, file_publisher_href, **kwargs):  # noqa: E501
        """Inspect a file publisher  # noqa: E501

        ViewSet for File Publishers.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.publishers_file_file_read(file_publisher_href, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str file_publisher_href: URI of File Publisher. e.g.: /pulp/api/v3/publishers/file/file/1/ (required)
        :return: FilePublisher
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.publishers_file_file_read_with_http_info(file_publisher_href, **kwargs)  # noqa: E501
        else:
            (data) = self.publishers_file_file_read_with_http_info(file_publisher_href, **kwargs)  # noqa: E501
            return data

    def publishers_file_file_read_with_http_info(self, file_publisher_href, **kwargs):  # noqa: E501
        """Inspect a file publisher  # noqa: E501

        ViewSet for File Publishers.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.publishers_file_file_read_with_http_info(file_publisher_href, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str file_publisher_href: URI of File Publisher. e.g.: /pulp/api/v3/publishers/file/file/1/ (required)
        :return: FilePublisher
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['file_publisher_href']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method publishers_file_file_read" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'file_publisher_href' is set
        if ('file_publisher_href' not in local_var_params or
                local_var_params['file_publisher_href'] is None):
            raise ApiValueError("Missing the required parameter `file_publisher_href` when calling `publishers_file_file_read`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'file_publisher_href' in local_var_params:
            path_params['file_publisher_href'] = local_var_params['file_publisher_href']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Basic']  # noqa: E501

        return self.api_client.call_api(
            '{file_publisher_href}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='FilePublisher',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def publishers_file_file_update(self, file_publisher_href, data, **kwargs):  # noqa: E501
        """Update a file publisher  # noqa: E501

        Trigger an asynchronous update task  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.publishers_file_file_update(file_publisher_href, data, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str file_publisher_href: URI of File Publisher. e.g.: /pulp/api/v3/publishers/file/file/1/ (required)
        :param FilePublisher data: (required)
        :return: AsyncOperationResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.publishers_file_file_update_with_http_info(file_publisher_href, data, **kwargs)  # noqa: E501
        else:
            (data) = self.publishers_file_file_update_with_http_info(file_publisher_href, data, **kwargs)  # noqa: E501
            return data

    def publishers_file_file_update_with_http_info(self, file_publisher_href, data, **kwargs):  # noqa: E501
        """Update a file publisher  # noqa: E501

        Trigger an asynchronous update task  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.publishers_file_file_update_with_http_info(file_publisher_href, data, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str file_publisher_href: URI of File Publisher. e.g.: /pulp/api/v3/publishers/file/file/1/ (required)
        :param FilePublisher data: (required)
        :return: AsyncOperationResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['file_publisher_href', 'data']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method publishers_file_file_update" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'file_publisher_href' is set
        if ('file_publisher_href' not in local_var_params or
                local_var_params['file_publisher_href'] is None):
            raise ApiValueError("Missing the required parameter `file_publisher_href` when calling `publishers_file_file_update`")  # noqa: E501
        # verify the required parameter 'data' is set
        if ('data' not in local_var_params or
                local_var_params['data'] is None):
            raise ApiValueError("Missing the required parameter `data` when calling `publishers_file_file_update`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'file_publisher_href' in local_var_params:
            path_params['file_publisher_href'] = local_var_params['file_publisher_href']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'data' in local_var_params:
            body_params = local_var_params['data']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Basic']  # noqa: E501

        return self.api_client.call_api(
            '{file_publisher_href}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='AsyncOperationResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)
