# Generated by Django 2.0.13 on 2019-05-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_fiobank_payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiopayment',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Note'),
        ),
    ]
