
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-05-13T10:53:54+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "cde0e55ecd8211ff5a4bd5904987b785e2f1041c",
 "version": "0.6.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
