
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-05-08T07:46:05-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "d6e507c9c20cace62df087f7bcaaff8f2d21fddc",
 "version": "3.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
