# coding: utf-8

"""
    Bleumi Pay API

    The power of fiat at the speed of cryptocurrency  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from bleumi_pay.api_client import ApiClient


class GasApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def estimate_gas(self, network, addr, **kwargs):  # noqa: E501
        """Returns the current expected gas price  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.estimate_gas(network, addr, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param EthNetwork network: (required)
        :param EthAddress addr: ERC20 Token Address (required)
        :return: EstimatedGas
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.estimate_gas_with_http_info(network, addr, **kwargs)  # noqa: E501
        else:
            (data) = self.estimate_gas_with_http_info(network, addr, **kwargs)  # noqa: E501
            return data

    def estimate_gas_with_http_info(self, network, addr, **kwargs):  # noqa: E501
        """Returns the current expected gas price  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.estimate_gas_with_http_info(network, addr, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param EthNetwork network: (required)
        :param EthAddress addr: ERC20 Token Address (required)
        :return: EstimatedGas
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['network', 'addr']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method estimate_gas" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'network' is set
        if ('network' not in params or
                params['network'] is None):
            raise ValueError("Missing the required parameter `network` when calling `estimate_gas`")  # noqa: E501
        # verify the required parameter 'addr' is set
        if ('addr' not in params or
                params['addr'] is None):
            raise ValueError("Missing the required parameter `addr` when calling `estimate_gas`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'network' in params:
            query_params.append(('network', params['network']))  # noqa: E501
        if 'addr' in params:
            query_params.append(('addr', params['addr']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['ApiKeyAuth']  # noqa: E501

        return self.api_client.call_api(
            '/v1/gas/estimate', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='EstimatedGas',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
